- hosts: "{{ hosts }}"
  connection: local
  gather_facts: no
  user: root

# Install/uninstall with chocolatey
- name: Ensure 7-Zip is installed via Chocolatey
  win_chocolatey:
    name: 7zip
    state: present
